=== saasify-sh/saasify/packages/saasify-cli/lib/schemas/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Config",
  "definitions": {
    "Config": {
      "title": "Config",
      "type": "object",
      "properties": {
        "saasifyVersion": {
          "title": "saasifyVersion",
          "default": 1,
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "version": {
          "title": "version",
          "default": "0.1.0",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "name": {
          "type": "string",
          "title": "name"
        },
        "description": {
          "type": "string",
          "title": "description"
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "title": "keywords"
        },
        "alias": {
          "type": "string",
          "title": "alias"
        },
        "build": {
          "type": "object",
          "title": "build",
          "additionalProperties": true
        },
        "env": {
          "type": "object",
          "title": "env",
          "additionalProperties": true
        },
        "saas": {
          "type": "object",
          "title": "saas",
          "additionalProperties": true
        },
        "openapi": {
          "title": "openapi",
          "type": "string"
        },
        "backendUrl": {
          "title": "backendUrl",
          "type": "string"
        },
        "backendDevUrl": {
          "title": "backendDevUrl",
          "type": "string"
        },
        "services": {
          "type": "array",
          "title": "services",
          "items": {
            "$ref": "#/definitions/Service"
          }
        },
        "enableCoupons": {
          "type": "boolean",
          "title": "enableCoupons"
        },
        "webhooks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Webhook"
          },
          "title": "webhooks"
        },
        "headers": {
          "type": "object",
          "title": "headers",
          "additionalProperties": true
        },
        "immutable": {
          "type": "boolean",
          "title": "immutable"
        },
        "authProviders": {
          "title": "authProviders",
          "$ref": "#/definitions/AuthProviderMap"
        },
        "proxyMode": {
          "title": "proxyMode",
          "enum": ["passive", "active"]
        },
        "pricingPlans": {
          "type": "array",
          "minItems": 1,
          "maxItems": 5,
          "items": {
            "$ref": "#/definitions/PricingPlan"
          },
          "title": "pricingPlans"
        }
      },
      "additionalProperties": false
    },
    "Example": {
      "title": "Example",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "description": {
          "type": "string",
          "title": "description"
        },
        "input": {
          "type": "object",
          "title": "input"
        },
        "inputContentType": {
          "type": "string",
          "title": "inputContentType"
        },
        "output": {
          "title": "output"
        },
        "snippet": {
          "$ref": "#/definitions/Snippet",
          "title": "snippet"
        },
        "additionalProperties": false
      },
      "required": ["name", "input"]
    },
    "Webhook": {
      "title": "Webhook",
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "title": "url"
        },
        "events": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "title": "events"
        },
        "additionalProperties": false
      },
      "required": ["url"]
    },
    "Service": {
      "title": "Service",
      "type": "object",
      "properties": {
        "src": {
          "type": "string",
          "title": "src"
        },
        "name": {
          "type": "string",
          "title": "name"
        },
        "path": {
          "type": "string",
          "title": "path"
        },
        "timeout": {
          "type": "number",
          "title": "timeout"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Example"
          },
          "title": "examples"
        },
        "config": {
          "type": "object",
          "title": "config",
          "additionalProperties": true
        },
        "httpMethod": {
          "title": "httpMethod",
          "default": "get",
          "enum": [
            "get",
            "put",
            "post",
            "delete",
            "head",
            "trace",
            "patch",
            "GET",
            "PUT",
            "POST",
            "DELETE",
            "HEAD",
            "TRACE",
            "PATCH"
          ]
        },
        "headers": {
          "type": "object",
          "title": "headers",
          "additionalProperties": true
        },
        "immutable": {
          "type": "boolean",
          "title": "immutable"
        },
        "reportUsage": {
          "type": "boolean",
          "title": "reportUsage"
        },
        "rateLimit": {
          "oneOf": [
            { "$ref": "#/definitions/RateLimit" },
            { "type": "null" },
            { "type": "string" }
          ],
          "title": "rateLimit"
        },
        "pricingPlanConfig": {
          "type": "object",
          "title": "pricingPlanConfig",
          "patternProperties": {
            "^.*$": { "$ref": "#/definitions/PricingPlanServiceConfig" }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "RateLimit": {
      "title": "RateLimit",
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "title": "enabled",
          "default": true
        },
        "desc": {
          "type": "string",
          "title": "desc"
        },
        "requestsInterval": {
          "title": "requestsInterval",
          "default": "1h",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "requestsMaxPerInterval": {
          "type": "number",
          "title": "requestsMaxPerInterval",
          "default": 1000
        }
      },
      "additionalProperties": false
    },
    "Snippet": {
      "title": "Snippet",
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "title": "label"
        },
        "language": {
          "type": "string",
          "title": "language"
        },
        "code": {
          "type": "string",
          "title": "code"
        },
        "exclusive": {
          "type": "boolean",
          "title": "exclusive",
          "default": true
        }
      },
      "additionalProperties": false,
      "required": ["label", "language", "code"]
    },
    "PricingPlan": {
      "title": "PricingPlan",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "slug": {
          "type": "string",
          "title": "slug"
        },
        "desc": {
          "type": "string",
          "title": "desc"
        },
        "auth": {
          "type": "boolean",
          "title": "auth"
        },
        "features": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "title": "features"
        },
        "amount": {
          "type": "number",
          "title": "amount",
          "default": 0,
          "minimum": 0
        },
        "trialPeriodDays": {
          "type": "number",
          "title": "amount",
          "minimum": 0
        },
        "requests": {
          "$ref": "#/definitions/PricingPlanMetricConfig",
          "title": "requests"
        },
        "metrics": {
          "title": "metrics",
          "type": "array",
          "items": {
            "$ref": "#/definitions/PricingPlanMetricConfig"
          }
        },
        "rateLimit": {
          "oneOf": [
            { "$ref": "#/definitions/RateLimit" },
            { "type": "null" },
            { "type": "string" }
          ],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false,
      "required": ["name"]
    },
    "PricingPlanMetricConfig": {
      "title": "PricingPlanMetricConfig",
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "title": "amount",
          "minimum": 0
        },
        "slug": {
          "type": "string",
          "title": "slug"
        },
        "label": {
          "type": "string",
          "title": "label"
        },
        "unitLabel": {
          "type": "string",
          "title": "unitLabel"
        },
        "usageType": {
          "type": "string",
          "title": "usageType",
          "enum": ["metered", "licensed"]
        },
        "billingScheme": {
          "type": "string",
          "title": "billingScheme",
          "enum": ["per_unit", "tiered"]
        },
        "tiersMode": {
          "type": "string",
          "title": "teirsMode",
          "enum": ["graduated", "volume"]
        },
        "tiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PricingPlanTier"
          },
          "title": "tiers"
        },
        "rateLimit": {
          "oneOf": [
            { "$ref": "#/definitions/RateLimit" },
            { "type": "null" },
            { "type": "string" }
          ],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false
    },
    "PricingPlanTier": {
      "title": "PricingPlanTier",
      "type": "object",
      "properties": {
        "unitAmount": {
          "type": "number",
          "title": "unitAmount",
          "minimum": 0
        },
        "flatAmount": {
          "type": "number",
          "title": "flatAmount",
          "minimum": 0
        },
        "upTo": {
          "title": "upTo",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        }
      },
      "additionalProperties": false,
      "required": ["upTo"]
    },
    "PricingPlanServiceConfig": {
      "title": "PricingPlanServiceConfig",
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "title": "enabled"
        },
        "reportUsage": {
          "type": "boolean",
          "title": "reportUsage"
        },
        "rateLimit": {
          "oneOf": [
            { "$ref": "#/definitions/RateLimit" },
            { "type": "null" },
            { "type": "string" }
          ],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false
    },
    "AuthProviderMap": {
      "title": "AuthProviderMap",
      "type": "object",
      "properties": {
        "github": {
          "title": "github",
          "$ref": "#/definitions/AuthProviderConfig"
        },
        "google": {
          "title": "google",
          "$ref": "#/definitions/AuthProviderConfig"
        },
        "spotify": {
          "title": "spotify",
          "$ref": "#/definitions/AuthProviderConfig"
        },
        "linkedin": {
          "title": "linkedin",
          "$ref": "#/definitions/AuthProviderConfig"
        },
        "twitter": {
          "title": "twitter",
          "$ref": "#/definitions/AuthProviderConfig"
        },
        "default": {
          "title": "default",
          "$ref": "#/definitions/AuthProviderConfig"
        }
      },
      "additionalProperties": false
    },
    "AuthProviderConfig": {
      "title": "AuthProvideronfig",
      "type": "object",
      "properties": {
        "enabled": {
          "title": "enabled",
          "type": "boolean"
        },
        "clientId": {
          "title": "clientId",
          "type": "string"
        },
        "clientSecret": {
          "title": "clientSecret",
          "type": "string"
        },
        "scopes": {
          "title": "scopes",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== saasify-sh/saasify/docs/includes/puppet-master-saasify.json
{
  "name": "puppet-master",
  "services": [
    {
      "src": "src/screenshot.ts",
      "examples": [
        {
          "name": "Basic",
          "input": {
            "url": "https://youtube.com"
          }
        },
        {
          "name": "Custom",
          "input": {
            "url": "https://github.com",
            "type": "jpeg",
            "quality": 90,
            "viewport": {
              "width": 1920,
              "height": 1080,
              "deviceScaleFactor": 2
            },
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
          }
        }
      ]
    },
    {
      "src": "src/pdf.ts",
      "examples": [
        {
          "name": "Basic",
          "input": {
            "url": "https://producthunt.com"
          }
        }
      ]
    }
  ],
  "saas": {
    "name": "Puppet Master",
    "heading": "Puppeteer as a Service",
    "subheading": "Control headless Chrome via a simple SaaS API!",
    "repo": "https://github.com/saasify-sh/puppet-master",
    "logo": "./media/logo.svg",
    "favicon": "./media/favicon.ico"
  },
  "env": {
    "EXAMPLE_DYNAMIC_ENV_VAR": "@my-dynamic-secret",
    "EXAMPLE_STATIC_ENV_VAR": "foobar"
  }
}
